---

#- hosts: k3s_cluster
#  gather_facts: yes
#  become: yes
#  roles:
#    - role: prereq
#    - role: download
#
- hosts: master[0]
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: k3s/restore

      #- hosts: master
      #  become: yes
      #  roles:
      #    - role: k3s/master
      #
      #- hosts: node
      #  become: yes
      #  roles:
      #    - role: k3s/node
