# Generated by Django 3.0.1 on 2024-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=80, unique=True)),
                ('vm_ip', models.CharField(max_length=80)),
                ('vm_ssh_user', models.CharField(max_length=80)),
                ('vm_ssh_pass', models.CharField(max_length=80)),
                ('vm_ssh_port', models.CharField(max_length=80)),
            ],
        ),
    ]
