# Generated by Django 3.0.1 on 2024-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20241010_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_name',
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kvm',
            name='vm_ip_reachable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_ip_reachable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_usable',
            field=models.BooleanField(default=True),
        ),
    ]
